Use project name from MANIFEST in cado script

diff --git a/cado b/cado
--- a/cado
+++ b/cado
@@ -27,13 +27,17 @@
 #      make [-j N] [TARGET]
 #
 
-this_project=SPS
-
+this_project=`cat MANIFEST | sed -n '/NAME/s/.*: //p'`
+                   
             cmake_command='cmake -S . -B ${build_dir}  "$@"'
      cmake_static_command='cmake -S . -B ${build_dir}  -DSTATIC_INTEL=ON "$@"'
         cmake_all_command='WITH_SYSTEM_RPN=FALSE cmake -S . -B ${build_dir} "$@"'
       cmake_debug_command='cmake -S . -B ${build_dir}  -DCMAKE_BUILD_TYPE=Debug" $@"'
 cmake_debug_extra_command='cmake -S . -B ${build_dir}  -DCMAKE_BUILD_TYPE=Debug" -DEXTRA_CHECKS_ON $@"'
+       cmake_mach_command='cmake -S . -B ${build_dir}  -DWITH_MACH=TRUE "$@"'
+cmake_mach_static_command='cmake -S . -B ${build_dir}  -DWITH_MACH=TRUE -DSTATIC_INTEL=ON "$@"'
+   cmake_all_mach_command='WITH_SYSTEM_RPN=FALSE cmake -S . -B ${build_dir}  -DWITH_MACH=TRUE "$@"'
+ cmake_mach_debug_command='cmake -S . -B ${build_dir}  -DWITH_MACH=TRUE -DCMAKE_BUILD_TYPE=Debug" $@"'
 
   build_command='cmake --build ${build_dir} -- "$@"'
    work_command='cmake --build ${build_dir} --target work -- "$@"'
@@ -121,32 +125,24 @@ See \`cado --help\` for more detailed info
 "
 }
 
-
-# Variable to generalize: SPS_ARCH used to compose build_dir and its name
-# is used in the text below.  Could be
-# ${SPS_ARCH} -> $(eval echo \${${this_project}_ARCH}) (in the if)
-# \${SPS_ARCH} -> \${${this_project}_ARCH} (in the text)
-# build_dir=$(realpath build-$(eval echo \${${this_project}_ARCH}))
-if [[ -z $(eval echo \${${this_project}_ARCH}) ]] ; then
-    echo "$0: This convenience helper uses \${${this_project}_ARCH} to set the cmake build"
-    echo "and install directories as build-\${${this_project}_ARCH} and work-\${${this_project}_ARCH}"
+this_project_upper=$(echo ${this_project} | tr '[:lower:]' '[:upper:]')
+if [[ -z $(eval echo \${${this_project_upper}_ARCH}) ]] ; then
+    echo "$0: This convenience helper uses \${${this_project_upper}_ARCH} to set the cmake build"
+    echo "and install directories as build-\${${this_project_upper}_ARCH} and work-\${${this_project_upper}_ARCH}"
     echo "but the variable is not set.  This indicates that the environment"
     echo "setup 'source .common_setup <compiler>' has not been done.  This"
     echo "is necessary for the build with or without this helper."
     exit 1
 fi
 
-# Variable to generalize: SPS_GIT_DIR used for this check only.
-# SPS_GIT_DIR -> $(eval echo \${this_project}_GIT_DIR})
 this_project_lower=$(echo ${this_project} | tr '[:upper:]' '[:lower:]')
 if [[ $(realpath $PWD) != $(realpath $(eval echo \${${this_project_lower}_DIR})) ]] ; then
   printf "$0: \033[1;31mERROR\033[0m: This command must be run from the top of the source code repository\n"
   exit 1
 fi
-# The above could be replaced by a `cd` to ${sps_DIR}
 
-if ! build_dir=$(realpath build-$(eval echo \${${this_project}_ARCH})) ; then
-    echo "ERROR running true_path on 'build-\${SPS_ARCH}'."
+if ! build_dir=$(realpath build-$(eval echo \${${this_project_upper}_ARCH})) ; then
+    echo "ERROR running true_path on 'build-\${this_project_upper}_ARCH}'."
 fi
 echo "Using build directory '${build_dir}'"
 
@@ -160,6 +156,10 @@ case "${name}" in
             cmake-all) cmd=${cmake_all_command} ;;
           cmake-debug) cmd=${cmake_debug_command} ;;
     cmake-debug-extra) cmd=${cmake_debug_extra_command} ;;
+           cmake-mach) cmd=${cmake_mach_command} ;;
+    cmake-mach-static) cmd=${cmake_mach_static_command} ;;
+       cmake-all-mach) cmd=${cmake_all_mach_command} ;;
+     cmake-mach-debug) cmd=${cmake_mach_debug_command} ;;
                 build) cmd=${build_command} ;;
                  work) cmd=${work_command} ;;
               install) cmd=${install_command} ;;
